### ISSUE TITLE
麻烦将博客里我的联系方式去掉

### ISSUE THREAD

**Issue by mzlogin** [big-mouth-cn/blog#1]
Hi~冒昧打扰，我是您使用的博客模板的作者。

最近遇到有两个人通过微博、微信等找到我，然后发给我一个 m.cat-happy.cn 的网址问我一些东西，但实际这并不是我的内容。

我询问下发现他们是找到这个博客 www.cat-happy.cn ，然后联系到我的。

麻烦将 https://github.com/big-mouth-cn/blog/blob/master/_data/social.yml 里的内容删掉或者修改成您自己的吧～以便有需要的人联系到想找的人。

**Comment by big-mouth-cn** [comment]
好的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Zhuang Ma ***@***.***&gt;
发送时间: 2022年4月7日 18:54
收件人: big-mouth-cn/blog ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[big-mouth-cn/blog] 麻烦将博客里我的联系方式去掉 (Issue #1)





 
Hi~冒昧打扰，我是您使用的博客模板的作者。
 
最近遇到有两个人通过微博、微信等找到我，然后发给我一个 m.cat-happy.cn 的网址问我一些东西，但实际这并不是我的内容。
 
我询问下发现他们是找到这个博客 www.cat-happy.cn，然后联系到我的。
 
麻烦将 https://github.com/big-mouth-cn/blog/blob/master/_data/social.yml 里的内容删掉或者修改成您自己的吧～以便有需要的人联系到想找的人。
